export const PAYMENT_METHODS = {
  CARD: 'card',
  STRIPE: 'stripe',
  TRANSFER: 'transfer',
};

export const ALLOWED_PAYMENT_METHODS = [PAYMENT_METHODS.CARD, PAYMENT_METHODS.STRIPE, PAYMENT_METHODS.TRANSFER];
export const ALLOWED_CURRENCY = ['usd'];
